[project]
name = "mcp-multiskill"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "argparse-to-json>=0.0.1",
    "mcp[cli]>=1.26.0",
]
