[project]
name = "simple-memory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp-multiskill[skill-need]",
]

[tool.uv.sources]
mcp-multiskill = { path = "../../", editable = true }

